### PR TITLE
Create B.3_DILI-one-hop-from-genes.trapi

### PR DESCRIPTION
**Pull request by andrewsu**
straw man for how to organize TRAPI queries for the demo

### CODE REVIEW

**Comment by andrewsu** [comment]
I suggest that we stick with a fixed naming scheme.  For example, in `B.3_DILI-one-hop-from-genes.trapi`, `B.3` refers to workflow B query 3, `DILI-one-hop-from-genes` is a short descriptive slug, and `.trapi` emphasizes that this should be a full TRAPI query.

**Comment by karafecho** [comment]
I like this suggestion a lot. I also think we should have separate tickets for each TRAPI query. Unless others disagree, I will reorganize the Workflow B queries that I posted.

**Review by cbizon — COMMENTED** [review]
I think this is great.  Two thoughts:

Should we have another level of organization so that it looks like:
2021-12_demo/workflowB/B.3_DILI-one-hop-from-genes.trapi

Should the extension be .json?

**Comment by andrewsu** [comment]
Great suggestions -- added to the PR!

**Comment by diatomsRcool** [comment]
I like this too. I think it can be merged and all workflow champions should be instructed to add their TRAPI queries in this manner.

**Pull request merged**
